### ISSUE TITLE
How with weebly

### ISSUE THREAD

**Issue by david0077** [maschek/imgmap#84]
Hello, how can i integrate that html code in weebly?

Please help.

David

**Comment by maschek** [comment]
Hi David,

In weebly you have to use "Embed Code" to insert custom HTML. If you host your image also on Weebly, then you have to upload your image in a normal image container and get the URL of it. It is a bit tricky, I have created a screencast to show you how to do it.
Please shoot me an email to adam.maschek - at - gmail.com and I send you the link to the video.

Cheers,
Adam
